#!/usr/bin/python3
import sys
def main(argv):
    try:
        if argv[0][0] == "-":
            subtitle = Subtitle(argv)
            subtitle.run_options()
            subtitle.end_program()
        else:
            print(0)
            Subtitle.wrong_command()

    except IndexError:
        print(1)
        Subtitle.wrong_command()

class Subtitle:

    def __init__(self, arg_list):
        self.arg_list = arg_list
        self.sub_read = self._set_read_and_write('r')

    def run_options(self):
        if self.arg_list[0][1] == "h":
            self.help_command()
        elif self.arg_list[0][1] == "r":
            print(self.read_sub())
        elif self.arg_list[0][1] == "w":
            self.write_sub()

    def read_sub(self):
        return self.sub_read.read()

    def _set_read_and_write(self, rw):
        try:
            return open(self.arg_list[1], rw)
        except Exception:
            self.wrong_command()

    def write_sub(self):
        sub_write = self._set_read_and_write('w')
        sub_write.write(self.arg_list[2])
        sub_write.close()

    def end_program(self):
        self.sub_read.close()
        raise SystemExit(0)

    @staticmethod
    def help_command():
        print("commands are:")
        print("-h: shows all commands")
        print("-r: read the subtitle file")
        print("-a: add amount to subtitle in miliseconds")
        print("-s: subtract amount to subtitle in miliseconds")
        print("usage: -(option) path/to/subtitlefile amount_to_subtract_or_add")
        raise SystemExit(0)

    @staticmethod
    def wrong_command():
        print("you made a mistake in your arguments")
        print("this is the -h option:")
        Subtitle.help_command()


if __name__ == "__main__":
   main(sys.argv[1:])

