#!/usr/bin/python3
from Subtitle import Subtitle
import sys
def main(argv):
    try:
        if argv[0][0] == "-":
            subtitle = Subtitle(argv)
            subtitle.error_checks()
            subtitle.run_options()
            subtitle.end_program()
        else:
            Subtitle.wrong_command()

    except IndexError:
        Subtitle.wrong_command()

if __name__ == "__main__":
   main(sys.argv[1:])
